package overlay

// Injector is implemented by Bridge for use in the engine's Send path.
// The engine calls PendingSystemReminder at turn start to obtain any
// screen-context reminder generated by the most recent ContextUpdate.
//
// Phase 7 will wire this into the engine's Send path so the context is
// prepended to the outgoing user message. For Phase 6, the interface is
// exposed and Bridge stores the pending reminder; the actual prepend is
// deferred.
type Injector interface {
	// PendingSystemReminder returns the current pending <system-reminder> block
	// and clears it. Returns "" if no update is pending.
	PendingSystemReminder() string
}
